format_version: 5
pipelines:
  hello-world-dev:
    group: gdp
    materials:
      repo:
        git: git@github.com:noel-rapido/hello-world.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              elastic_profile_id: hermes
              artifacts:
                - build:
                    source: build-state.json
                    destination: artifacts
              tasks:
                - exec:
                    command: hermes
                    arguments:
                      - build
                      - manual
                      - -e
                      - development
                      - -o
                      - build-state.json
                      - -f
                      - pipelines/skaffold.yaml
      - deploy:
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            deploy:
              elastic_profile_id: hermes
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: artifacts/build-state.json
                    is_file: yes
                - exec:
                    command: hermes
                    arguments:
                      - deploy
                      - manual
                      - -e
                      - development
                      - -c
                      - backend
                      - -a
                      - build-state.json
                      - -f
                      - pipelines/skaffold.yaml
