apiVersion: skaffold/v2beta5
kind: Config
build:
  artifacts:
    - image: asia.gcr.io/staging-host-12358/hello-world
      docker:
        dockerfile: Dockerfile
  local:
    push: true
    useDockerCLI: true
  tagPolicy:
    envTemplate:
      template: "v1.0.0"

profiles:
  - name: development
    deploy:
      statusCheckDeadlineSeconds: 300
      helm:
        releases:
          - name: hello-world
            namespace: services
            chartPath: ./helm-charts/hello-world
            valuesFiles:
              - ./helm-charts/hello-world/values.yaml
