apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
    stack: golang
    team: devops
  name: hello-world
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: hello-world
      team: devops
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
        team: devops
    spec:
      containers:
        - image: asia.gcr.io/staging-host-12358/hello-world:v1.0.0
          imagePullPolicy: Always
          name: hello-world
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP