apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world
    team: devops
  name: hello-world
  namespace: test
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-world
  type: ClusterIP
status:
  loadBalancer: {}